define(function() {
    return {
        getStudentLeaveRecords: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getStudentLeaveRecords.do',
        getStudentLeaveRecordDetails: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getStudentLeaveRecordDetails.do',
        checkWhetherStudentCanApply: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/checkWhetherStudentCanApply.do',
        saveStudentLeaveRecord: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/saveStudentLeaveRecord.do',
        getDictionaryOfLeaveType: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getDictionaryOfLeaveType.do',
        queryDetailApplyInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/queryDetailApplyInfo.do',
        getLeaveType: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getLeaveType.do',
        recallApplyInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/recallApplyInfo.do',
        delLeaveInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/delLeaveInfo.do',
        getAppliedDays: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getAppliedDays.do',

        getStudentApplyRecords: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getStudentApplyRecords.do',
        queryCurrentState: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/queryCurrentState.do',
        getStudentApplyDetail: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getStudentApplyDetail.do',
        getDictionaryOfShzt: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getDictionaryOfShzt.do',
        getDictionaryOfXjzt: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getDictionaryOfXjzt.do',
        getDictionaryOfXjlx: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getDictionaryOfXjlx.do',
        auditSubmit: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/auditSubmit.do',
        removeLeaveSubmit: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/removeLeaveSubmit.do',
        queryStudentInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/queryStudentInfo.do',
        saveStudentApply: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/saveStudentApply.do',
        getDictionaryOfFrontState: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getDictionaryOfFrontState.do',
        querySfbz: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/querySfbz.do',
        recallAuditInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/recallAuditInfo.do',
        getLeaveTypeByLxdm: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getLeaveTypeByLxdm.do',
        getDWZXInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getDWZXInfo.do',
        getDwpzHzw: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/getDwpzHzw.do',
        setDWXJ: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/setDWXJ.do',
        checkDWXJSwitch: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceStudentApply/checkDWXJSwitch.do',
        getLeaveSet: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getLeaveSet.do',
        /** 查询统计 **/
        getMxbDataInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/getMxbDataInfo.do',
        getAdvancedQuery: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/getAdvancedQuery.do',
        queryAllZy: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/queryAllZy.do',
        queryAllBj: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/queryAllBj.do',
        queryAllSyBj: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/queryAllSYBj.do',
        getMxbXq: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/getMxbXq.do',
        cxdqxn: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/cxdqxn.do',
        getTjbDataInfo: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/teacherCxtj/getTjbDataInfo.do',
        
        /* 续假 */
        saveContinueApply : WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/ContinueApply/saveContinueApply.do',
        getAuditInfo : WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/MobileServiceTeacherAudit/getAuditInfo.do',
        editExtendLeaveApply : WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/ContinueApply/editExtendLeaveApply.do',
        
        //集体请假
        getHasQx: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getHasQx.do',
        getShzt: WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getShzt.do',
        getCurrentShzt:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getCurrentShzt.do',
        getJtApplyList:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getJtApplyList.do',
        getAllStudent:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getAllStudent.do',
        getSqbh:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getSqbh.do',
        getNjs:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getNjs.do',
        getYxs:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getYxs.do',
        getZys:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getZys.do',
        getBjs:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getBjs.do',
        saveXzry:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/saveXzry.do',
        saveJtqj:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/saveJtqj.do',
        getYtjrs:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getYtjrs.do',
        deleteJtshryxx:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/deleteJtshryxx.do',
        getJtqjxxxx:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getJtqjxxxx.do',
        getFrontState:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getFrontState.do',
        callBackJtsq:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/callBackJtsq.do',
        getQjrqs:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getQjrqs.do',
        singleAudit:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/singleAudit.do',
        getApplyAndAuditInfo:WIS_CONFIG.ROOT_PATH + '/sys/swmxsqjapp/modules/jtsh/getApplyAndAuditInfo.do'
    };
});